# Build customization
builds:
  - binary: terraform-provider-auth0
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
      - 386
    ignore:
      - goos: darwin
        goarch: 386

# Archive customization
archive:
  format: zip

  replacements:
    amd64: 64-bits
    386: 32-bits
    darwin: macOS

  files:
- nothing.*